### ISSUE TITLE
Rendre la librairie multi-instances

### ISSUE THREAD

**Issue by yheynema** [TechnoPhysCAL/TGP_Decodeur#6]
Actuellement, version 1.1.1 ne supporte pas le multi-instance dans une même application. En effet, les variables d'une instance étant globales, en cas de déclaration d'une seconde instance, cette dernière prime et la 1ere est "perdue".

Le use-case est celui d'un ESP qui recoit et décode les messages entrant d'un port série physique mais fait de même pour un second port série, tout en traitant distinctivement. Ce use-case est préparé pour le labo sur la communication sérielle du cours de Mécatronique à l'hiver 2024.

Pour l'instant j'ai du dupliquer la librairie (Décodeur2) et renommer les variables "globales" dans le .cpp (et qqe define dans le .h) pour faire fonctionner le use-case ci-haut.

Pour donner une idée:
[TGP_Decodeur2.zip](https://github.com/TechnoPhysCAL/TGP_Decodeur/files/14013784/TGP_Decodeur2.zip)

Le use-case est ce fichier, qui devrait être installé sur 2x ESP32 reliés par une paire de fils via RX2/TX2:
[ESP32_RS232-protocole_Labo01_manip2_Yh_jan2024.zip](https://github.com/TechnoPhysCAL/TGP_Decodeur/files/14013823/ESP32_RS232-protocole_Labo01_manip2_Yh_jan2024.zip)

**Comment by yheynema** [comment]
J'ai testé la version 2.0.0 de la lib et ... ça ne marche pas... je crois qu'il subsiste tjrs une confusion à l'initialisation. Je crois que le problème se situe au niveau de code .cpp   la section entre les lignes 17 à 21 qui devront être spécifiquement placées sous la déclaration private de l'objet, dans le .h, par exemple:
```
class Decodeur
{

public:
	Decodeur(Stream *stream);
	Decodeur(Stream *stream, char separateur, int base);
	bool available();
	int getArgCount();
	char getCommand();
	String getCommandString();
	float getArg(int);
	String getArgString(int);

private:
	bool lireBuffer();
	void updateArgCount();
	float convertirArg(String p, int base);
	int HexaToDecimal(const char *Hexa);
	
	String _instruction; // Buffer pour emmagasiner le dernier message reçu
	int _NbArg;			 // Variable pour le nombre d'arguments contenu dans le message
	char _separateur;	 // Charactère de séparation dans le message
	int _base;			 // Variable pour contenir la base numérique (Entier, flottant ou hexadécimal)
	Stream *_MyStream;	 // Pointeur pour permettre de sélectionner l'objet de communication Stream

};
```

**Comment by dualB** [comment]
Bonjour, la modification a été apportée, pouvez-vous tester svp? Merci!

**Comment by yheynema** [comment]
Excellent, selon les derniers tests, tout fonctionne... le code de test utilisé était fort probablement le coupable en allant jouer avec le port série directement.
