### ISSUE TITLE
Mieux filtrer les char reçus au buffer de reception

### ISSUE THREAD

**Issue by yheynema** [TechnoPhysCAL/TGP_Decodeur#7]
S'il arrive qu'un caractère null (00) soit reçu au Serial, vaudrait mieux l'éliminer du buffer car s'il le fait, il y aura un Core Panic de la part du ESP32. Cette situation arrive régulièrement si le mode de transmission employé est RS485. En effet, un caractère NULL (00) s'inscrit dans la communication et cause le problème (crash). La comm RS485 expérimente ceci car elle est half-duplex et le transceiver utilisé cause une transition sur la broche RX.
Ainsi voici ce qui a marché, modification de lireBuffer():
```
[...]
// Lecture du byte reçu et ajout au Buffer de reception
		_IncomingByte = _MyStream->read();
		**if (_IncomingByte > 0) {  //Yh-22janv24 pour hic avec RS485 du ESP32**
			_InComBuffer[_InComIndex] = _IncomingByte; //Ajoute le byte reçu dans dans le buffer
			++_InComIndex;
			_InComBuffer[_InComIndex] = '\0'; //Déplace le caractère de fin de chaine
		}
[...]
```

**Comment by TechnoPhysCAL** [comment]
Dans la nouvelle version, le buffer est maintenant en format String. Par sécurité, le caractère \0 est recherché dans la String, bien que ce soit possible qu'elle n'y existe jamais.
